---
title: "Artificial Hydrocarbon Networks in R"
author: "Jose Roberto Ayala Solares"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ahnr_vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

`ahnr` is a package that implements the artificial hydrocarbon networks developed by [Hiram Ponce](http://www.solariumlabs.com/hiram_ponce.html). Most of the work is based on the book [Artificial Organic Networks](http://www.springer.com/gb/book/9783319024714).

## Quick Start

Here are some quick examples to get you started. To visualize the plots, make sure you have the packages `ggplot2` and `ggthemes` installed.

### Create a mixture

```{r Example 1 Training}
library(ahnr)

# Create data
set.seed(12321)
x <- 2 * runif(1000) - 1;
x <- sort(x)

y <- (x < 0.1) * (0.05 * runif(100) + atan(pi*x)) + 
    (x >= 0.1 & x < 0.6) * (0.05 * runif(1000) + sin(pi*x)) + 
    (x >= 0.6) * (0.05 * runif(1000) + cos(pi*x))

plot(x, y, type = 'l')

# Create the Sigma dataset
Sigma <- list(X = data.frame(x = x), Y = data.frame(y = y))

# Create network
ahn <- AHNnD(Sigma, 5, 0.01, 500)
```

### Simulate a network

```{r Example 1 Simulation}
# Create test data
X <- data.frame(x = x)
ysim <- SimAHNnD(ahn, X)

plot(x, y, type = 'l')
lines(x, ysim, type = 'l', col = 'red')
```

### 2D problem
